# Generated by Django 4.2.2 on 2023-06-09 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remotefanapi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fan',
        ),
    ]
