# Generated by Django 4.2.2 on 2023-06-09 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remotefanapi', '0002_delete_fan'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='address',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
