# Generated by Django 4.2.2 on 2023-06-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remotefanapi', '0003_bar_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bar',
            name='teams',
        ),
        migrations.AddField(
            model_name='team',
            name='bars',
            field=models.ManyToManyField(related_name='teamBars', to='remotefanapi.bar'),
        ),
    ]
