# Generated by Django 4.2.2 on 2023-06-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remotefanapi', '0004_remove_bar_teams_team_bars'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='teams',
            field=models.ManyToManyField(related_name='barTeams', to='remotefanapi.team'),
        ),
    ]
