# Generated by Django 4.2.2 on 2023-06-19 20:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remotefanapi', '0005_bar_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='logo',
            field=cloudinary.models.CloudinaryField(default=True, max_length=255, verbose_name='image'),
        ),
    ]
