# Generated by Django 4.2.2 on 2023-06-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remotefanapi', '0007_alter_team_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='logo',
            field=models.URLField(blank=True),
        ),
    ]
